### PR TITLE
Removing (most of) os.path

### PR DESCRIPTION
**Pull request by LucasLev**
Hey, following my comment on reddit I quickly edited you code to make a better use of pathlib. 

I think pathlib is the way to go here, as it's way more readable when managing filesystem than the os.path submodule.

I also removed the contextlib that was only used to remove errors, as it was only used to silence an error that is desirable with the pathlilb mkdir (i.e. if a file already with the same name than the folder exists, then something very strange happened earlier and we should better stop now and investigate).

The only line I haven't changed is the strange os.makedirs(f"{True}"), because that seemed very odd to me and I didn't want to break anything.

### CODE REVIEW

**Comment by LucasLev** [comment]
I think I solved my internal conflict about l889, I will look at it in around 3h and add a fix, wait until then to merge

**Comment by AbhiK002** [comment]
Damn! I had no idea pathlib works like that. Thank you very much for this info... I'll now remember this for future projects. Ah sure 😄 3 hours then.

**Comment by LucasLev** [comment]
There ! All good

**Comment by AbhiK002** [comment]
Merging now, Thanks again for the help!

**Pull request merged**
